[build] 
    command = "pip install -r requirements.txt"
    functions = "netlify/functions"
    publish = "."
    environment = { PYTHON_VERSION = "3.9" } 

[build.environment] 
    PYTHON_VERSION = "3.9" 
    
[functions] 
    directory = "netlify/functions" 
     
[[redirects]] 
    from = "/*" to = "/.netlify/functions/app" 
    status = 200
